### ISSUE TITLE
How to get current Purchase when I complete the purchase

### ISSUE THREAD

**Issue by sceneren** [mvojtkovszky/BillingHelper#10]
How to get current Purchase when I complete the purchase？ My product may be purchased repeatedly. And How to get all OwnedPurchases?

**Comment by mvojtkovszky** [comment]
you can do
`billingHelper.getPurchaseWithProductName("yourProductName")`
This will return a `Purchase`only if purchased.

Additionally, you can check for that explicitly using
`billingHelper.isPurchased("yourProductName")`
