### ISSUE TITLE
Suggestion and Help

### ISSUE THREAD

**Issue by MaxAndolini** [mvojtkovszky/BillingHelper#2]
I am using anjlab's library for subscriptions on the app. But it's terrible. When people cancel the subscription. It never informs us and Google told AIDL is deprecated. Can you give me info about your library and comparisons. At the end, can you help me for migration.

https://github.com/anjlab/android-inapp-billing-v3

**Comment by mvojtkovszky** [comment]
Hi Ercan,

It should be quite easy to migrate really as the library is pretty straightforward to use. Following the Readme should give you about all the info needed.

**Comment by MaxAndolini** [comment]
Hi again,

Your library based on Kotlin and I need Java version of that. Can you help me about that? And readme etc.

@mvojtkovszky

**Comment by mvojtkovszky** [comment]
@MaxAndolini works with Java out of the box. Readme lists all of the public methods which are then fully documented.

**Comment by MaxAndolini** [comment]
@mvojtkovszky  Can you help me with Discord? I could not do that transform.
