### ISSUE TITLE
Where should I pass my OWN KEY ?

### ISSUE THREAD

**Issue by crismaver1993** [mvojtkovszky/BillingHelper#3]
should be something like:
`
key = BuildConfig.DONATIONS_KEY`

billing = BillingHelper(
            context = this,
            skuInAppPurchases =subsList,
            skuSubscriptions = listOf(),
            billingListener = this,
            querySkuDetailsOnConnected = true,
            queryOwnedPurchasesOnConnected = true,
            autoAcknowledgePurchases = true,
            **key = BuildConfig.MY_OWN_KEY**
        )

**Comment by mvojtkovszky** [comment]
Helper is bassed on Google Play Billing Library v4, which requires no key.

**Comment by mvojtkovszky** [comment]
Not supported yet, but added to backlog.
You're also free to make a pull request with a solution, if needed somewhat urgently.

**Comment by mvojtkovszky** [comment]
Added in 1.8.0
