### ISSUE TITLE
Doing purchase on internal test getting error.

### ISSUE THREAD

**Issue by abcbitlab123** [mvojtkovszky/BillingHelper#6]
Bug Description
Summary:
The app functions normally for testers who have been granted permissions, but for other users, a popup error appears stating: "Error: This item you were attempting to purchase could not be found."

Steps to Reproduce:

1. Setup the app according to the provided instructions.
2. Upload the app to internal testing.
3. Test the app with users who do not have granted permissions.
4. I'm review on production but the app name always mark as unreviewed.
Expected Result:
The app should function normally for all users.

Actual Result:
The app shows a popup error for users without permissions: "Error: This item you were attempting to purchase could not be found.". Billing Response code = 4  ITEM_UNAVAILABLE

Additional Information:

The issue does not occur for testers who have been granted permissions.
The problem persists only for other users.
Possible Solution:
To fix this issue, ensure that the item or feature in question is available to all users or check the configuration for the internal testing setup. Verify that the necessary permissions and access rights are properly set for all users.

Feel free to let me know if you need any additional information or assistance!.

Please help me in this case. I'm a newbie and really excited in with your source code.

**Comment by mvojtkovszky** [comment]
Sounds like the Google's Billing APIs simply doesn't return products for users without granted permissions in internal testing, if app is not available publicly?

**Comment by abcbitlab123** [comment]
Im trying to publish my app to production. But policy team tell that my app is violate policy because when i run purchase flow the purchase bottom sheet show that error. Do you have any idea. Please help me!
