### ISSUE TITLE
[Feature Request] Support subscription update/upgrade

### ISSUE THREAD

**Issue by darkokoa** [mvojtkovszky/BillingHelper#9]
Hi, I notice that BillingHelper doesn't support subscription updates (upgrading from one plan to another). Would it be possible to add this feature?

**Comment by mvojtkovszky** [comment]
Certainly - it will be included in the next release.

Until then you can use the latest [snapshot version](https://github.com/mvojtkovszky/BillingHelper/commit/0263f97ee1c0cc1e6a006d8f1936296a5e4d3343) where the feature was just added. 

Let me know if it works as expected.

**Comment by darkokoa** [comment]
Hi, keep you waiting for a long time

Currently encountering two issues when updating subscriptions:

#### Issue 1: IllegalArgumentException
Getting error message: "Please provide Old SKU purchase information (token/id) or original external transaction id, not both"

Root cause: 
The implementation allows both `subscriptionUpdateOldName` and `subscriptionUpdateExternalTransactionId` to be set simultaneously, while Play Billing Library requires using only one of these parameters

#### Issue 2: Invalid Token Error
When trying to update subscription plan (e.g., from monthly to yearly plan of the same subscription), getting "Invalid token" message from BillingListener `onBillingEvent()`

Root cause: I don't know why 😢

**Comment by darkokoa** [comment]
OK, regarding issue2, I have found the root cause

In the current implementation, `setOldPurchaseToken()` uses the parameter `subscriptionUpdateOldName` - if we pass the old subscription name, it will definitely result in the error mentioned above. When I changed it to use the actual OldPurchaseToken (for example, `billing.getPurchaseWithProductName(xxx)?.purchaseToken`), the subscription update was successful

**Comment by mvojtkovszky** [comment]
I see, there was a sloppy oversight from my end, i renamed it to `subscriptionUpdateOldToken` instead which should clear out the confusion.
I also changed it so either `subscriptionUpdateOldToken` or `subscriptionUpdateExternalTransactionId` must be supplied in order for update parameters to be build, but not enforcing logic whether both or either is allowed - since Google's Billing provides clear messaging regarding potential miss-use
